modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "structurecredits"
version = "${version}"
displayName = "Structure Credits"
authors = "ECarrascon"
description = '''
Automatically displays the name and mod source of any structure upon entry, ensuring easy recognition and credit for mod creators.
'''
#logoFile = ""

[[dependencies.structurecredits]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.structurecredits]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.structurecredits]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "structurecredits.mixins.json"